{{- if .Values.back.hpa.enabled -}}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: back-hpa
spec:
  maxReplicas: {{ .Values.back.hpa.maxReplicas }}
  minReplicas: {{ .Values.back.hpa.minReplicas }}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: backend-laravel
  metrics:
    {{- if .Values.back.hpa.averageCpuUtilization }}
    - type: Resource
      resource:
        name: cpu
        target:
            type: Utilization
            averageUtilization: {{ .Values.back.hpa.averageCpuUtilization }}
    {{- end }}
{{- end }}

# https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale-walkthrough/