apiVersion: v1
kind: Service
metadata:
  name: laravel-service
spec:
  type: NodePort
  selector:
    app: backend-laravel
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: backend-laravel
  name: backend-laravel
spec:
  replicas: {{ .Values.back.replicaCount }}
  selector:
    matchLabels:
      app: laravel-back
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: laravel-back
    spec:
      containers:
        - image: {{ .Values.back.image.laravel_image }}
          name: laravel-back
          imagePullPolicy: {{ .Values.back.image.pullPolicy }}
          ports:
            - containerPort: 8000
status: {}
