apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-service
spec:
  selector:
    app: rabbitmq
  ports:
    - port: 5672
  clusterIP: None
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rabbitmq
spec:
  selector:
    matchLabels:
      app: rabbitmq
  serviceName: rabbitmq-service
  replicas: {{ $.Values.rabbitmq.replicaCount }}
  template:
    metadata:
      name: rabbitmq
      labels:
        app: rabbitmq
    spec:
      containers:
        - image: {{ $.Values.rabbitmq.image }}
          name: rabbitmq
          env:
          - name: RABBITMQ_ERL_COOKIE
            valueFrom:
              secretKeyRef:
                name: rabbitmq-secret
                key: erlcookie
          ports:
            - containerPort: 5672
              name: rabbitmq
          volumeMounts:
            - name: rabbitmq-persistent-storage
              mountPath: /var/lib/rabbitmq
      volumes:
        - name: rabbitmq-persistent-storage
          persistentVolumeClaim:
            claimName: rabbitmq-pv-claim
